package br.edu.fatec.paises.enums;

import java.util.Arrays;
import java.util.ResourceBundle;

public enum AppText {

    SCREEN_NAME_MENU(), LOGGER_INIT_APP(),

    // SCREEN MENU
    LBL_TITLE_MENU(), LBL_CURRENT_LANGUAGE(), BTN_NEW_COUNTRY(), BTN_REGISTER_NEIGHBOR(),
    BTN_MANAGE_COUNTRY(), BTN_LIST_COUNTRIES(), LBL_NAME_GITHUB(), LBL_DEVELOPERS(),
    MSG_OPTION_PANE_COUNTRIES_EMPTY(), MSG_OPTION_PANE_NEW_COUNTRY(), BTN_OPTION_PANE_MENU(),
    LINK_GITHUB(), MSG_ERROR(),

    // SCREEN COUNTRY REGISTRATION
    LBL_TITLE_COUNTRY_REGISTRATION(), LBL_COUNTRY_NAME(), LBL_COUNTRY_CAPITAL(), LBL_COUNTRY_DIMENSION(),
    LBL_INFO_COUNTRY_SUCCESS_TEXT(), LBL_INFO_COUNTRY_EXISTING(), LBL_INFO_EMPTY_FIELD(), LBL_INFO_INVALID_TEXT_SIZE(),
    LBL_INFO_INVALID_NUMBER_FIELD(), BTN_SAVE(), BTN_MENU(), BTN_EDIT_COUNTRY(), BTN_CANCEL(),
    LBL_OPTION_TITLE_CREATE_COUNTRY_CONFIRM(), BTN_OPTION_SAVE(),

    // SCREEN NEIGHBORING COUNTRY REGISTRATION
    LBL_TITLE_NEIGHBOR_REGISTER(), LBL_SELECT_COUNTRY(), LBL_SELECT_NEIGHBOR(), BTN_SELECT(),
    LBL_INFO_NEIGHBOR_SUCCESS_TEXT(), LBL_INFO_COUNTRY_SELECTED(), LBL_INFO_LIST_EMPTY(),
    BTN_REGISTER(), LBL_OPTION_TITLE_COUNTRY_CHANGE(), MSG_OPTION_CHANGE_COUNTRY_SELECTED(),
    MSG_OPTION_WARNING_CLEAR_LIST(), BTN_OPTION_CHANGE(),

    // SCREEN COUNTRY MANAGER
    LBL_TITLE_MANAGER_COUNTRY(), BTN_DELETE_COUNTRY(), BTN_DELETE_NEIGHBOR(), LBL_INFO_SUCCESS_COUNTRY_DELETED(),
    LBL_INFO_SUCCESS_NEIGHBOR_DELETED(), LBL_INFO_SUCCESS_COUNTRY_EDITED(), LBL_OPTION_TITLE_CONFIRM_COUNTRY_DELETE(),
    MSG_OPTION_CONFIRM_COUNTRY_DELETE(), MSG_OPTION_CONFIRM_NEIGHBOR_DELETE(), BTN_OPTION_DELETE(),
    LBL_OPTION_TITLE_WARNING(), MSG_OPTION_LIST_COUNTRY_EMPTY(), MSG_OPTION_BACKING_MENU(),

    // SCREEN COUNTRY LIST
    LBL_TITLE_COUNTRY_LIST(), LBL_ORDERING_TITLE(), BTN_NAME(), BTN_CAPITAL(),
    BTN_DIMENSION(), LBL_QTD_COUNTRIES(), LBL_NEIGHBORS(), MSG_LIST_NEIGHBOR_EMPTY(),

    // SCREEN DEVELOPERS
    LBL_TITLE_DEVELOPERS(),

    // INTERFACE PANEL SETTINGS
    MSG_CONFIRM(), MSG_WARNING(), BTN_CONFIRM(), MSG_ERROR_MOUNT_SCREEN(),

    // ENTITY COUNTRY
    PRINT_FRONTIER(), PRINT_COUNTRY();

    private static String language = "lang/AppText_pt_BR";

    public static AppText getEnum(String string) {
        return Arrays.stream(AppText.values())
                .filter(menuText -> menuText.getString().equals(string))
                .findFirst().orElse(null);
    }

    public static void changeLanguage(String language) {
        AppText.language = language;
    }

    public static String getLanguage() {
        return language;
    }

    public String getString() {
        return ResourceBundle.getBundle(getLanguage()).getString(name());
    }
}